# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Memories in the Time of Covid 19
email: brianjbutcher65@gmail.com
description: > # this means to ignore newlines until "baseurl:" What it says on the tin:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brianbutcher.life" # the base hostname & protocol for your site

collections:
  pages:
    output: true
  spacetime:
    output: false
  essays:
    output: true
  experimental:
    output: true
  birdsofdb:
    output: true
  bird-classification:
    output: true

# Build settings
markdown: kramdown
